### ISSUE TITLE
for BigDecimal it is responding 0

### ISSUE THREAD

**Issue by bewithdhanu** [organics2016/pojo2json#1]
BigDecimal should give 1.01 like this, but it is responding like 0
in the same way for Double also

**Comment by organics2016** [comment]
Thank you for lssues.
Previously, BigDecimal was considered a subset of numeric types.
In the next release, I'll optimize the return results for decimal types.

**Comment by bewithdhanu** [comment]
looking forward to that update, Thanks

**Comment by organics2016** [comment]
Fix to v1.0.7 and Submitted to plugin repository , Jetbrains audit takes two business days.

**Comment by bewithdhanu** [comment]
I'm seeing v1.0.5 version in Android Studio, is this the latest version?

**Comment by organics2016** [comment]
v1.0.5 not latest&nbsp;version, v1.0.7 is latest version but this version is being reviewed.
It's supposed to be the second working day by today.









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dhanu K Parvateesam"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午3:24
收件人:&nbsp;"organics2016/pojo2json"<pojo2json@noreply.github.com&gt;;
抄送:&nbsp;"Tony"<374564811@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [organics2016/pojo2json] for BigDecimal it is responding 0 (#1)




I'm seeing v1.0.5 version in Android Studio, is this the latest version?

**Comment by organics2016** [comment]
It should be update to the latest version tomorrow.
