### ISSUE TITLE
一个低级需要改进的体验

### ISSUE THREAD

**Issue by hopana** [organics2016/pojo2json#12]
其实插件做的挺好的，一直也在使用，很方便，感谢作者！
不过有一个个人感觉比较低级，也很容易可以改进的地方，那就是：
在javabean转JSON的时候，为啥把serialVersionUID、日志框架的log变量这种 final statis 的全局变量也转成JSON属性？没必要吧
我觉得可以过滤一下类似这种的变量，起码serialVersionUID是完全可以过滤的，日志框架的log变量不知道可不可以动态识别，如果可以，那应该也可以过滤掉，这样体验就更好了。

目前我每次都是自己手动删除，比较麻烦，强烈建议改进！！！

**Comment by organics2016** [comment]
HI，
感谢您的建议。
可以很容易过滤指定字段或类型。除了您提到的serialVersionUID，log
还有 static ，transient , final ，甚至是class持有自身引用，等这类字段都是考虑的情况。
程序目前对这方面的处理还是采用保守策略，有两个原因
1、我想尽量保证对象结构的完整性
2、这个程序设计之初的工作场景是在一个无状态的POJO上。
根据您的建议我会对上面这些场景再整理一下。
我想以 Jackson 库的处理策略为准，即如果Jackson对上面哪些情况会采用 过滤 或 保留，呢么我也会照做。
这么做的好处是如果你发现json结果中出现不应该出现的字段，呢么这个字段也会被送到前端。

待我去Jackson上测试测试，在改进前这个Issue不会被关闭。

**Comment by organics2016** [comment]
HI hopana，
你说的没错，调查发现 jackson 策略认为 static的成员不应该与类的实例相关，只与类相关。
下个版本将会过滤掉所有 被static标识的成员变量，这与Jackson序列化行为相同。 

这个改进会包含在 release 1.1.4 中，两个工作日内可通过 jetbrains plugins 推送或手动拉取更新。
