### ISSUE TITLE
Add java.util.UUID support

### ISSUE THREAD

**Issue by maximen39** [organics2016/pojo2json#13]
Pls, add java.util.UUID support
![image](https://user-images.githubusercontent.com/21176163/150646952-7012ea8c-674e-4e3e-b982-fb3ff3f2491b.png)

Good solution:
```
{
  "matchUuid": "da99afcb-909c-468d-8e14-a1608b75816e"
}
```

**Comment by organics2016** [comment]
Thank your issue, it's next release.

**Comment by organics2016** [comment]
support from release 1.1.5
