### ISSUE TITLE
Record classes throw error "Can't find class scope"

### ISSUE THREAD

**Issue by christoph360** [organics2016/pojo2json#14]
Hello,
first I want to thank you very much for that great plugin, that saves alot of time.

I might found a bug using the plugin with Java record classes. Classes that uses the new `record` keyword fail to create JSON body. IntelliJ shows the following error message: **Can't find class scope**

![image](https://user-images.githubusercontent.com/12587361/151027721-fd2dfaa4-855d-4a17-b5f1-51f410df1919.png)

**Comment by organics2016** [comment]
Hi,
Thank you for your issue. Parsing `record` is not supported at this time. I haven't tested in the environment above jdk11.
I will support it in the next version.

**Comment by organics2016** [comment]
Support from release 1.1.6

Updates can be pushed or pulled manually within two business days via jetbrains plugins.
