### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by hopana** [organics2016/pojo2json#15]
我觉得插件做的挺好，用起来很方便！给作者点赞！！！
但是有个低级的不好的体验可以改进一下：
javabean转json的时候，过滤一下serialVersionUID、log4j的log全局实例变量。
这两个东西一般没人会需要转成json属性吧，每次都要手动去删，太麻烦了。 不知道楼主能不能改善一下！

**Comment by organics2016** [comment]
#12 
这个问题不是已经解决了么。
你用的是哪个版本？

**Comment by organics2016** [comment]
从1.1.4版本之后，所有被声明为static的成员变量会被过滤。不会再被转换为json。
呢么你所提到的serialVersionUID、log4j等变量如果是static就不会再被转成json。
如果你定义的这些变量不是static 你的考虑你这么做是为什么。你所提到的属性看起来都不与类的实例相关，应该都是static的。
