### ISSUE TITLE
Support for member class

### ISSUE THREAD

**Issue by ducanh2110** [organics2016/pojo2json#17]
Hi team. I have problem with nested class in side another class. Plugin always generate the parent class not the child class. Any chance for support like that?

**Comment by organics2016** [comment]
Thanks for your issues.
Can you give me an class example

**Comment by ducanh2110** [comment]
Thanks for supporting. My example like:
Class A {
 class B {}
}.
And I want to generate class B with their attributes. But now only generate from class A

**Comment by organics2016** [comment]
Okay, Add in next version.
The next version only the class where the cursor is located is parsed. If the cursor is not in any class, the first class in the file is parsed.

**Comment by ducanh2110** [comment]
Thanks so much for supporting so fast. I will wait for next release. Thanks again
