### ISSUE TITLE
功能请求：模拟实际使用的随机值

### ISSUE THREAD

**Issue by willser** [organics2016/pojo2json#18]
感谢你们的贡献，这个项目对我的帮助非常大，现在有一个功能请求：

对于字符串类型的随机值目前生成的都是同一个值，期望根据字段名的不同产生不同的值。比如：

xxxName 生成 Tom Jerry 张三 李四

xxxUrl 生成 http://demo.com

xxxAddress 生成 China  USA

**Comment by organics2016** [comment]
感谢你的建议。遗憾的是这个建议在短期内不会支持，并且没有计划支持。具体历史原因如下：

这个需求之前有被提到过， #3 
我也尝试过一些实现，其中有一种实现就是针对 关键字 的提取，导致了类似于下面的问题
{"fileName":"张三",
"signName":"李四",
"urlPrefix":"http://demo.com",
"uriSuffix","http://demo1.com"}

1、这很明显脱离业务语境（或者说上下文语境），我认为程序不给出有效建议 要比 给出错误的建议好。即使用户可以对结果进行调整，懒于调整是大多数情况，这并不利于减少和 tester 或 dba 的摩擦。 
2、混乱的值导致用户需要大量修改时变得不方便（不便于全局替换）, 对于一些强表单校验的业务而言，这不能有效减少工作量，反而会增加。
3、变量中出现name 或 结尾是name 这个变量大概率描述的是人的名称？但实际情况是恰好相反，这是个小概率事件。url ，uri 也是如此，很多带有url 的变量，用户真正使用时赋值是hash或者id。

因为上面的这些问题这个临时实现最终被放弃，没有推送到稳定版。

这个建议短期不会被关闭，可以继续讨论。

**Comment by aimilin6688** [comment]
是否可以添加一个设置项？按照 【字段名_随机字符串】 的形式生成值，而不解析字段真实业务含义

**Comment by organics2016** [comment]
暂时搞了个随机字符串
https://github.com/organics2016/pojo2json/commit/841f3083f5c544bbcd98cc7ca73e4feefaf2b54c

**Comment by lunasaw** [comment]
java doc 可以复制到注释吗，虽然json 协议上不支持注释操作，但给前端透出协议的时候 真的很好用
类似
public class User{
/**
* 用户ID
*/
 private Long id;
}

-----------------》

{ "id":"" // 用户ID}

**Comment by organics2016** [comment]
> java doc 可以复制到注释吗，虽然json 协议上不支持注释操作，但给前端透出协议的时候 真的很好用 类似 public class User{ /**
> 
> * 用户ID
>   */
>   private Long id;
>   }
> 
> -----------------》
> 
> { "id":"" // 用户ID}

简单的方法是 toJSONString 后二次处理这个 String ，这样不用考虑处理类型，先在这记录一下。
之前想搞，觉的太麻烦了，而且最后的结果不被大多数语法检查器认可，看的很奇怪，就没再搞了。

**Comment by organics2016** [comment]
Fix to 2.0.1 and last version.
