### ISSUE TITLE
不进入到类里也能工作-改进建议

### ISSUE THREAD

**Issue by zhanggang807** [organics2016/pojo2json#2]
现在使用方法是需要进到类中，然后点击右键
希望能在类使用处或者变量使用处 右键也能生成json
比如List<DemoBean> 右键DemoBean也可生成json
或者选中之后再右键，省去进入到类里那一步

**Comment by organics2016** [comment]
> 现在使用方法是需要进到类中，然后点击右键
> 希望能在类使用处或者变量使用处 右键也能生成json
> 比如List 右键DemoBean也可生成json
> 或者选中之后再右键，省去进入到类里那一步

非常感谢您的建议。
目前程序默认json的最外层为一个object，在变量类型或者变量名处提取其类型需要处理一些例外情况，
例如选定 int 或者 integer 的变量是否视为json中的一个object还是直接抛出异常 ，诸如此类的一些特殊对象的列举等，需要花时间整理。
这个issue不会关闭，直到完善后。
