### ISSUE TITLE
Consider adding the possibility of setting max string size for random values

### ISSUE THREAD

**Issue by setofaces** [organics2016/pojo2json#21]
Hi there. Really awesome plugin man.  It will be really great feature to have variable with maximum string length for generating random values. Best wishes.

**Comment by organics2016** [comment]
Thanks for your support. The plugin itself doesn't want to give a meaningful string value. Business meaning or Form validation requires user customization.
If this needs a lot, I might work on the `@javax.validation.constraints.Size`

**Comment by Endeavour17** [comment]
Hello, you did awesome work! The plugin itself doesn't want to give a meaningful string value - so can you consider to add customizing random string? Now it's [hardcoded](https://github.com/organics2016/pojo2json/blob/ab72c9b937fa9b42ede10919ad274d5419bd800b/src/main/java/ink/organics/pojo2json/parser/type/StringType.java#L18) like "test_ + random uuid" and it will be great if it can be customizible to, for example, without word `test` and underscore

**Comment by organics2016** [comment]
Thanks to your tips, it occurred to me that it could be configured in a way similar to EL expressions. I've never wanted to add redundant UI to the plugin, so didn't optimize here.
[Record it here.](https://docs.spring.io/spring-framework/reference/core/expressions.html)

**Comment by organics2016** [comment]
#18

**Comment by organics2016** [comment]
Fix to 2.0.1 and last version.
