### ISSUE TITLE
能支持继承的父类class文件吗

### ISSUE THREAD

**Issue by yangfeng20** [organics2016/pojo2json#23]
我有一个pojo，他继承了父类jar包中的class，但是生成出来的json没有父类class的字段

**Comment by organics2016** [comment]
是支持扫描父类的，你可以自己写个继承关系试试。
之所以扫描不到jar中的父类是因为你的jar包没有关联源码导致的，IDEA会给有源码的依赖创建index，这样你才能点过去，而这个插件就是靠这个索引扫描的，你需要首先确认一下IDEA是否能正确识别这个jar。并且按住ctrl键可以进入到jar中的源码文件 (*.java)

**Comment by yangfeng20** [comment]
就是说必须要是关联了源码的才可以是吧，点过去是java文件的那种才能行是吧。
但是我这个这个直接就是class文件也是可以支持的吧，拿到当前上下文的class，然后再去获取父类，这种不可以吗，是被idea屏蔽了吗

**Comment by organics2016** [comment]
也不是被IDEA屏蔽了，就是你在IDEA看到的class文件是IDEA帮你反编译过的，实际上字节码不是人可读的。
但IDEA也仅仅是反编译字节码，不会对字节码本身建立抽象语法树。而抽象语法树是IDEA对各种语言解析的基础，这个插件其实是调用IDEA提供的抽象语法树进行java语法解析的。
当然IDEA可能也提供了解析字节码并还原成抽象语法树的方法，也可能没有，但无论怎样至少IDEA的文档中没有提供相关信息。
https://www.jetbrains.com/help/idea/getting-started.html

**Comment by yangfeng20** [comment]
好的，那可以通过反射的方式实现吗，而不是通过idea提供的api，拿到这个class，然后去遍历所有field

**Comment by organics2016** [comment]
一般反射是在一个jvm实例下进行的，IDEA是反射不了你的项目的任何class文件的，IDEA和你的项目是不同的进程。IDEA 解析项目是通过它自己的语法树引擎实现的。你不能把IDEA看作是你项目的一部分吧

**Comment by yangfeng20** [comment]
明白了，懂了，多谢解惑哈

**Comment by yangfeng20** [comment]
可以这样实现吗，重写一个classLoader，从磁盘上面加载文件，就可以实现在idea项目中加载我的项目class了，然后就可以获取到class对象

**Comment by organics2016** [comment]
我觉得正确的做法是说服你的上游使用这个插件。
```
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.2.1</version>
```
包含源码不意味着开源或不安全，在私有repo中能得到更好的可维护性。在maven中央repo中包含src是必要条件。你应该检查你的jar是否合规，而不是把这看作一个工程问题。
https://central.sonatype.org/publish/publish-maven/#javadoc-and-sources-attachments
当然POJO to JSON是遵循MIT开源的，你可以实现你的任何想法。这里我们欢迎每个人的PR
