### ISSUE TITLE
快捷使用建议: 上调复制JSON的层级以及增加新的快捷栏目.

### ISSUE THREAD

**Issue by fwnan** [organics2016/pojo2json#25]
1.  上调层级到类的右键栏目,  在Paste之上我觉得都还可以. 比较方便快捷.
![image](https://user-images.githubusercontent.com/71653989/233895258-cfaa8a76-c799-4016-a2d4-009f9e9ea691.png)

2. 对类使用ALT+ENTER, 可以考虑在该栏目中增加COPY JSON的处理项, 该方式在无鼠标操作时比较方便. 
![image](https://user-images.githubusercontent.com/71653989/233895588-ddf00cb1-ebff-46a6-ad97-3d48333192c7.png)

**Comment by organics2016** [comment]
交互方式会在未来有所改变
