### ISSUE TITLE
大佬请教下，依赖包里的类无法转换么？

### ISSUE THREAD

**Issue by ReZeroS** [organics2016/pojo2json#27]
![image](https://github.com/organics2016/pojo2json/assets/13174606/706f6ced-07f3-4938-b648-46487efe42ab)

**Comment by ReZeroS** [comment]
找到了，需要在editor里触发就可以了
![image](https://github.com/organics2016/pojo2json/assets/13174606/a4a69746-445c-4b9a-a01c-2c11db2d75e5)

**Comment by organics2016** [comment]
https://github.com/organics2016/pojo2json/issues/23
