### ISSUE TITLE
Add sample / fake data values

### ISSUE THREAD

**Issue by spotlesscoder** [organics2016/pojo2json#3]
Everytime the functionality is accessed via the context menu, the resulting Json String's properties should be filled with sample data.
That might be done with a library like JavaFaker (https://www.baeldung.com/java-faker) or so.

**Comment by organics2016** [comment]
> Everytime the functionality is accessed via the context menu, the resulting Json String's properties should be filled with sample data.

Thank you for your issue.

Do you want these String's to be random?
eg : 
first convert  result   {"name":"aaa"} 
second convert  result  {"name":"bbb"}

Or it have value?
eg :
first convert  result   {"name":"test_string"} 
second convert  result  {"name":"test_string"}

**Comment by spotlesscoder** [comment]
Random would be great :)

**Comment by organics2016** [comment]
> Random would be great :)

I tried to do this and found some problems.

Some properties have business meaning
eg :
{"name":"Johe","phone":"1234567"}

Random values cannot override these business meanings  and It won't reduce the workload of test working and form validation

**Comment by spotlesscoder** [comment]
Maybe this will help https://www.baeldung.com/java-faker

**Comment by organics2016** [comment]
> Maybe this will help https://www.baeldung.com/java-faker

I've read this library
It is useful for value in key/value structures
eg:
{"name":"Johe"}  or {"name":"Tony"}

but I'm not sure what keys users use.
eg:
{"name":"Tony","firstName":"Archie","secondName":"Smith"}
or
{"tel":"1234567","phone":"1234567"}

I'm trying to extract some keywords such as "name" "tel" "address" ,but I'm not sure it can cover most of the business for  String's type.

But for other types, the value of the next version are more random
