### ISSUE TITLE
先前版本支持copy不生成随机值，现版本不支持？或在哪里设置。文档未说明

### ISSUE THREAD

**Issue by obill123** [organics2016/pojo2json#34]

**Comment by organics2016** [comment]
支持呀。默认就是不带随机值呀。你是说String类型有随机值嘛？

**Comment by obill123** [comment]
光标放置在类名上，右键只有Copy JSON选项和Column Selection Mode，尝试过都输出有随机值。先前版本我记得Copy JSON不输出随机值，有一个额外的选择Random...（抱歉具体名称忘了）才输出随机值。我不太清楚现在如何操作了，只有修改TOOLS里的表达式了吗

**Comment by organics2016** [comment]
https://github.com/organics2016/pojo2json/blob/master/README_ZH.md#configuration
两种配置，
第一种不带随机值
第二种带随机值
不管哪一种都是延用之前版本的两个选项的默认输出方式。
现在是精确到类型的配置，你想固定String类型的输出值可以这么配`java.lang.CharSequence=固定值`

**Comment by obill123** [comment]
![1701937075507](https://github.com/organics2016/pojo2json/assets/51981107/0ad2bce8-87c5-4efc-9b86-07e5de92639a)
我似乎找到问题所在了，我右键菜单没有Copy JSON and Random Values的选项。如图。来自IDEA 2023.1.3

**Comment by organics2016** [comment]
是的，因为我把Copy JSON and Random Values选项删了，
因为现在支持对单独的类型进行自定义值，你可以定义成随机的也可以是固定的。你想写什么值进去都可以，只要满足表达式就行了。
如果配置改乱了跑不起来，就把配置都删了然后保存，配置就自动恢复默认值了。

**Comment by obill123** [comment]
感谢解答，爱来自广东
