### ISSUE TITLE
目前不支持scala的case class，是否考虑适配一下scala的case class

### ISSUE THREAD

**Issue by laglangyue** [organics2016/pojo2json#35]

**Comment by organics2016** [comment]
我不确定Java and Kotlin 以外的jvm平台的支持情况。也没有计划支持。
我用了idea sdk的抽象语法树引擎实现语法解析。按照官方理论的说法它应该支持大多数jvm平台：[https://plugins.jetbrains.com/docs/intellij/uast.html#which-languages-are-supported](https://plugins.jetbrains.com/docs/intellij/uast.html#which-languages-are-supported)
但是这是一个很烂的实现，同一个接口会返回几种不同的结构，甚至直接返回null。我没有精力在这些实现上做多种平台的适配。
