### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by xbzhang1994** [organics2016/pojo2json#39]
如果能在类文件中根据选中的类生成JSON，而不是只生成当前类文件的JSON就更好了。比如下图：当我在当前类文件中选中了AppVersionBo类然后生成JSON。这样就不用在进入AppVersionBo类文件再去生成了，这样体验会更好！
![image](https://github.com/user-attachments/assets/09ae306f-d013-43c7-92c6-dbe13eb30d1a)

**Comment by organics2016** [comment]
现在难道不是这样吗？你确定光标在类字段上吗？

**Comment by xbzhang1994** [comment]
现在不是哦，选中之后转json没有任何用，粘贴板还是之前复制的东西。我用的版本是:2.0.6



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月26日 12:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [organics2016/pojo2json] 优化建议 (Issue #39) |

Closed #39 as completed.

**Comment by xbzhang1994** [comment]
IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
 ide.balloon.shadow.size=0
 ide.experimental.ui=true
Non-Bundled Plugins:
 dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
 Docker (233.14475.37)
 com.hxl.plugin.cool-request (2024.7.15)
 Lombook Plugin (233.14475.39)
 ink.organics.pojo2json (2.0.6)
 GrepConsole (13.0.2-IJ2023.3)
 org.asciidoctor.intellij.asciidoc (0.41.14)
 izhangzhihao.rainbow.brackets.lite (1.1.0)
 com.itangcent.idea.plugin.easy-yapi (2.7.2.212.0)
 com.baomidou.plugin.idea.mybatisx (1.6.3)
 wl-spring-assistant (1.4.6.222.241)
 cn.yiiguxing.plugin.translate (3.6.4)
Kotlin: 233.14475.28-IJ



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月26日 12:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [organics2016/pojo2json] 优化建议 (Issue #39) |

Closed #39 as completed.

**Comment by organics2016** [comment]
我可能描述不准确，光标需要在 变量的name上 ，而不是在变量的类型上
例如：
`private List<SimpleTestPOJO<String>> listField = new ArrayList<>();`
光标应该在 `listField` 上才会生效。
如果在类型上，插件会因为找不到元素默认返回当前文件的json.
至于为什么不支持在类型上转换，因为类型不一定就是object，有泛型和基本数据类型等一些特例，边界处理比较复杂。所以只会把整个变量作为一个元素。

**Comment by xbzhang1994** [comment]
好的，我试下，感谢。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月26日 19:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [organics2016/pojo2json] 优化建议 (Issue #39) |

我可能描述不准确，光标需要在 变量的name上 ，而不是在变量的类型上
例如：
private List<SimpleTestPOJO<String>> listField = new ArrayList<>();
光标应该在 listField 上才会生效。
如果在类型上，插件会因为找不到元素默认返回当前文件的json.
至于为什么不支持在类型上转换，因为类型不一定就是object，有泛型和基本数据类型等一些特例，边界处理比较复杂。所以只会把整个变量作为一个元素。
