### ISSUE TITLE
Backreferences not supported 

### ISSUE THREAD

**Issue by nazymko** [organics2016/pojo2json#4]
It has some issues with processing backreferences. In real use cases, it is a common situation to have a reference to the parent entity.

`This class reference level exceeds maximum limit or has nested references!`

**Comment by organics2016** [comment]
> It has some issues with processing backreferences. In real use cases, it is a common situation to have a reference to the parent entity.

Thank you for your issue.
Please give an example of a backreferences. I try to it. But I won't support it if it's the case below

When the program throws this warning there are only two possibilities
`This class reference level exceeds maximum limit or has nested references!`

1. This class reference level > 500
eg:
```
{
 {
  {
    .......501
  }
 }
}
```
2. This class or parent class has nested references
eg:
```
{
 "a":{
  "b":{
   "a":{
     "b":{
        .........
      }
    }
   }
 }
}
```
Perhaps both will happen for entity but this entity are not suitable for JSON.
This can cause memory overflows.
