### ISSUE TITLE
Support for Jackson for keyname

### ISSUE THREAD

**Issue by salujayatharth** [organics2016/pojo2json#5]
Using the following fieldName to populate the map, we can create actual json representation of the POJO class

String fieldName = field.getAnnotation(com.fasterxml.jackson.annotation.JsonProperty.class).value();
https://github.com/organics2016/pojo2json/blob/96d98d56d28e3a6648d8f6ed23bcc386317ec6ca/src/main/java/ink/organics/pojo2json/POJO2JsonAction.java#L162

**Comment by organics2016** [comment]
> Using the following fieldName to populate the map, we can create actual json representation of the POJO class
> 
> String fieldName = field.getAnnotation(com.fasterxml.jackson.annotation.JsonProperty.class).value();
> https://github.com/organics2016/pojo2json/blob/96d98d56d28e3a6648d8f6ed23bcc386317ec6ca/src/main/java/ink/organics/pojo2json/POJO2JsonAction.java#L162

Thank you for issue. I'll work on it in the next release.

**Comment by organics2016** [comment]
Fix to 1.0.11 version . It can updated on jetbrains plugins channel .
Thanks your feedback.
