### ISSUE TITLE
Intellj This class reference level exceeds maximum limit or has nested references!

### ISSUE THREAD

**Issue by broosted** [organics2016/pojo2json#6]
getting This class reference level exceeds maximum limit or has nested references!

**Comment by organics2016** [comment]
#4 
Is it?

**Comment by Linda-Tan** [comment]
This class reference level exceeds maximum limit or has nested references!

**Comment by Linda-Tan** [comment]
我发现不能存在@NotNull注解,所以是这样么?
有注解就会This class reference level exceeds maximum limit or has nested references!

**Comment by organics2016** [comment]
> 我发现不能存在@NotNull注解,所以是这样么?
> 有注解就会This class reference level exceeds maximum limit or has nested references!

不会，请检查你的类及父类的所有成员变量，看是否存在嵌套引用
